update pipelinerun.yaml

diff --git a/.tekton/pipelinerun.yaml b/.tekton/pipelinerun.yaml
--- a/.tekton/pipelinerun.yaml
+++ b/.tekton/pipelinerun.yaml
@@ -100,22 +100,60 @@ spec:
         params:
         - name: SCRIPT
           value: |
-            oc create deploy build-deploy --image="$(params.image)" -n image-builds
+            #!/bin/bash
+
+            Create_resources () {
+            oc create deploy build-deploy --image="$(params.image)" --replicas=0 -n image-builds
+            oc set resources deployment build-deploy --limits=cpu=200m,memory=256Mi --requests=cpu=100m,memory=125Mi -n image-builds
+
+            oc patch deployment build-deploy --type=merge -p '{"spec": {"template": {"spec": {"containers": [{"name": "build-deploy", "image": "$(params.image)", "livenessProbe": {"tcpSocket": {"port": 8080}, "initialDelaySeconds": 15, "periodSeconds": 10, "timeoutSeconds": 2, "failureThreshold": 3}, "readinessProbe": {"tcpSocket": {"port": 8080}, "initialDelaySeconds": 15, "periodSeconds": 10, "timeoutSeconds": 2, "failureThreshold": 3}}]}}}}' -n image-builds
+
+            oc create cm index --from-file=index.html -n image-builds
+            oc set volume deploy/build-deploy --add --configmap-name=index --mount-path=/var/www/html/ --name=index -n image-builds
+
             oc create svc clusterip build-deploy --tcp=8080:8080 -n image-builds
             oc create route edge build-deploy --service=build-deploy --insecure-policy=Redirect -n image-builds
-            #oc create deploy build-deploy-$(date "+%Y%m%d%H%M%S") --image="$(params.image)" -n image-builds
-            curl https://$(oc get route  build-deploy -o jsonpath='{.spec.host}' -n image-builds)
+            oc scale deploy build-deploy --replicas=1 -n image-builds
+            }
 
-            if [ $? -ne 0 ]
-              then
-                echo "failing"
-                exit 1
+            Clean_up () {
+             echo oc delete deploy build-deploy -n image-builds
+             echo oc delete cm index -n image-builds
+             echo oc delete svc build-deploy -n image-builds
+             echo oc delete route build-deploy -n image-builds
+            }
+
+            echo 'Creating resources to test the new image -- "$(params.image)" '
+            Create_resources
+
+
+            MAX_RETRIES=10
+            SLEEP_BETWEEN_RETRIES=2
+            ROUTE=$(oc get route build-deploy -o jsonpath='{.spec.host}' | tr -d '[:space:]')
+
+            attempt=1
+            while (( attempt <= MAX_RETRIES )); do
+              CURL=$(curl -s -o /dev/null -w "%{http_code}" "https://${ROUTE}")
+
+              if [[ "$CURL" == "200" ]]; then
+                echo "HTTP 200 received from ${ROUTE}"
+
+                Clean_up
+                exit 0
               else
-                echo "good - force error"
-                exit 1
-            fi
+                echo "Attempt $attempt/$MAX_RETRIES failed (HTTP $CURL). Retrying in $SLEEP_BETWEEN_RETRIES sec..."
+                (( attempt++ ))
+                sleep "$SLEEP_BETWEEN_RETRIES"
+              fi
+            done
+
+            echo "Failed to receive HTTP 200 from ${ROUTE} after $MAX_RETRIES attempts."
+            exit 1
         runAfter:
         - build-image
+        workspaces:
+          - name: source
+            workspace: source
         taskRef:
           params:
           - name: kind
