add basic ci test - 2

diff --git a/.tekton/pipelinerun.yaml b/.tekton/pipelinerun.yaml
--- a/.tekton/pipelinerun.yaml
+++ b/.tekton/pipelinerun.yaml
@@ -111,8 +111,8 @@ spec:
                 echo "failing"
                 exit 1
               else
-                echo "good"
-                exit 0
+                echo "good - force error"
+                exit 1
             fi
         runAfter:
         - build-image
